# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bolddeskchatsdk_ios_sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bolddeskchatsdk_ios_sample

pod 'bolddesk_chat_sdk', '~> 1.0.2'

end
